---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-secret
spec:
  selector:
    matchLabels:
      app: app-secret
  replicas: 3
  template:
    metadata:
      labels:
        app: app-secret
    spec:
      containers:
      - name: app-secret
        image: nginx:latest
        env:
        - name: USER
          valueFrom:
            secretKeyRef:
              name: db-user-pass
              key: username.txt
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-user-pass
              key: password.txt
        ports:
          - name: http
            containerPort: 80

