cat tk  apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: tkc-1
spec:
  distribution:
    version: v1.20.12
  topology:
    controlPlane:
      class: best-effort-small
      count: 1
      storageClass: kubernetes-storage-policy
    workers:
      class: best-effort-small
      count: 1
      storageClass: kubernetes-storage-policy
  settings:
    storage:
      classes: ["kubernetes-storage-policy"]
      defaultClass: kubernetes-storage-policy
    network:
     cni:
       name: antrea
     pods:
       cidrBlocks:
       - 10.96.0.0/16
     serviceDomain: cluster.local
     services:
       cidrBlocks:
       - 172.16.128.0/17